import mysql from 'mysql2/promise';
export const MAX_DB_INT=2147483647;
export function databaseConfig(env=process.env){if(env.DATABASE_URL)return env.DATABASE_URL;return{host:env.DB_HOST,port:Number(env.DB_PORT||3306),database:env.DB_NAME,user:env.DB_USER,password:env.DB_PASSWORD};}
export class MysqlAdapter{
 constructor(pool=mysql.createPool(databaseConfig())){this.pool=pool;}
 async loadRoom(code,connection=this.pool){const[[room]]=await connection.query('SELECT * FROM openclaw_dnp_rooms WHERE code=?',[code]);if(!room)return null;const[players]=await connection.query('SELECT * FROM openclaw_dnp_players WHERE room_id=? ORDER BY join_order',[room.id]);return map(room,players);}
 async refresh(code){return this.loadRoom(code);}
 async checkpoint(state,expectedVersion,players=state.players){const connection=await this.pool.getConnection();try{await connection.beginTransaction();const[result]=await connection.execute('UPDATE openclaw_dnp_rooms SET score_left=?,score_right=?,ball_x=?,ball_y=?,ball_vx=?,ball_vy=?,last_tick_at=NOW(3),version=version+1 WHERE id=? AND version=?',[state.scoreLeft,state.scoreRight,state.ballX,state.ballY,state.ballVx,state.ballVy,state.id,expectedVersion]);if(result.affectedRows!==1){const error=new Error('room checkpoint conflicted');error.code='DNP_CONFLICT';throw error;}const playerSeqs={};for(const p of players){const seq=Math.max(0,Math.min(MAX_DB_INT,p.inputSeq));const[updated]=await connection.execute('UPDATE openclaw_dnp_players SET input_position=?,input_seq=?,last_seen_at=NOW(3) WHERE id=? AND left_at IS NULL AND input_seq < ?',[p.inputPosition,seq,p.id,seq]);if(updated.affectedRows)playerSeqs[p.id]=seq;}await connection.commit();return{version:expectedVersion+1,playerSeqs};}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
 async touchPresence(playerIds){if(!playerIds.length)return;const placeholders=playerIds.map(()=>'?').join(',');await this.pool.execute(`UPDATE openclaw_dnp_players SET last_seen_at=NOW(3) WHERE left_at IS NULL AND id IN (${placeholders})`,playerIds);}
 async close(){await this.pool.end();}
}
function map(r,ps){return{id:r.id,code:r.code,mode:r.mode,status:r.status,adminPlayerId:r.admin_player_id,scoreLeft:r.score_left,scoreRight:r.score_right,ballX:r.ball_x,ballY:r.ball_y,ballVx:r.ball_vx,ballVy:r.ball_vy,version:r.version,lastTickAt:new Date(r.last_tick_at),players:ps.map(p=>({id:p.id,roomId:p.room_id,name:p.name,joinOrder:p.join_order,slotIndex:p.slot_index,inputPosition:p.input_position,inputSeq:p.input_seq,lastSeenAt:new Date(p.last_seen_at),leftAt:p.left_at?new Date(p.left_at):null}))};}
