import { advance } from './simulation.js';
export const MAX_INPUT_SEQ=2147483647;
const now=()=>Date.now();
const cloneInput=p=>({id:p.id,inputPosition:p.inputPosition,inputSeq:p.inputSeq});
export class RoomHub{
 constructor(code,adapter,onIdle,idleMs=30000,options={}){this.code=code;this.adapter=adapter;this.onIdle=onIdle;this.idleMs=idleMs;this.options={autoStart:true,presenceMs:10000,refreshMs:1000,inputRate:45,adminRate:5,maxBufferedAmount:1024*1024,maxBackpressureStrikes:3,finalCheckpointAttempts:5,finalCheckpointBackoffMs:10,simulationHz:60,snapshotHz:30,...options};this.clients=new Map();this.seq=0;this.dirty=false;this.stopped=false;this.quiesced=false;this.lastTick=now();this.lastRefresh=0;this.lastPresence=0;this.mutation=0;this.clientGeneration=0;this.pendingInputs=new Map();}
 async init(){this.state=await this.adapter.loadRoom(this.code);if(!this.state)throw new Error('room not found');this.startTimers();return this;}
 startTimers(){if(!this.options.autoStart||this.stopped||this.quiesced||this.tick)return;this.lastTick=now();this.tick=setInterval(()=>this.guard(()=>this.onTick()),1000/this.options.simulationHz);this.broadcast=setInterval(()=>this.guard(()=>this.onBroadcast()),1000/this.options.snapshotHz);this.checkpointTimer=setInterval(()=>this.guard(()=>this.checkpoint()),500);this.presenceTimer=setInterval(()=>this.guard(()=>this.touchPresence()),this.options.presenceMs);}
 pauseTimers(){clearInterval(this.tick);clearInterval(this.broadcast);clearInterval(this.checkpointTimer);clearInterval(this.presenceTimer);this.tick=null;this.broadcast=null;this.checkpointTimer=null;this.presenceTimer=null;}
 quiesce(){if(this.stopped)return;this.quiesced=true;this.pauseTimers();}
 resume(){if(this.stopped)return;this.quiesced=false;this.startTimers();}
 guard(fn){try{Promise.resolve(fn()).catch(error=>this.report(error));}catch(error){this.report(error);}}
 report(error){if(!this.stopped)console.error('dnp-ws hub error',this.code,error);}
 publicRoom(){const connected=new Set([...this.clients.values()].map(c=>c.playerId));return{code:this.state.code,mode:this.state.mode,status:this.state.status,version:this.state.version,adminPlayerId:this.state.adminPlayerId,scores:{left:this.state.scoreLeft,right:this.state.scoreRight},ball:{x:this.state.ballX,y:this.state.ballY,vx:this.state.ballVx,vy:this.state.ballVy},players:this.state.players.filter(p=>!p.leftAt).map(p=>({id:p.id,name:p.name,joinOrder:p.joinOrder,slotIndex:p.slotIndex,isAdmin:p.id===this.state.adminPlayerId,online:connected.has(p.id)||now()-new Date(p.lastSeenAt).getTime()<30000,input:p.inputPosition,inputSeq:p.inputSeq}))};}
 add(ws,claims){const player=this.state.players.find(p=>p.id===claims.playerId&&!p.leftAt);if(!player||this.stopped||ws.readyState!==1)return false;clearTimeout(this.idleTimer);this.finalizing=false;this.clientGeneration++;this.clients.set(ws,{playerId:player.id,inputCount:0,adminCount:0,backpressureStrikes:0,windowAt:now()});this.resume();return true;}
 remove(ws){if(!this.clients.delete(ws))return;this.clientGeneration++;if(!this.clients.size&&!this.stopped)this.scheduleIdleCleanup(this.clientGeneration);}
 scheduleIdleCleanup(generation){clearTimeout(this.idleTimer);this.idleTimer=setTimeout(()=>this.guard(()=>this.cleanupIdle(generation)),this.idleMs);}
 async cleanupIdle(generation){if(this.stopped||this.clients.size||generation!==this.clientGeneration)return;this.finalizing=true;this.quiesce();try{await this.checkpointUntilClean(this.options.finalCheckpointAttempts,()=>!this.clients.size&&generation===this.clientGeneration);}catch(error){this.finalizing=false;this.report(error);if(!this.clients.size&&!this.stopped&&generation===this.clientGeneration){this.resume();this.scheduleIdleCleanup(generation);}return;}if(this.stopped||this.clients.size||generation!==this.clientGeneration){this.finalizing=false;return;}this.stop();this.onIdle(this.code,this);}
 rate(client,key,limit){const at=now();if(at-client.windowAt>=1000){client.windowAt=at;client.inputCount=0;client.adminCount=0;}client[key]++;return client[key]<=limit;}
 input(ws,msg){const client=this.clients.get(ws),player=this.state.players.find(p=>p.id===client?.playerId&&!p.leftAt);if(!client||!player||!Number.isInteger(msg.seq)||msg.seq<0||msg.seq>MAX_INPUT_SEQ||typeof msg.position!=='number'||!Number.isFinite(msg.position))return;if(!this.rate(client,'inputCount',this.options.inputRate)){ws.close(4429,'input rate limit');return;}if(msg.seq<=player.inputSeq)return;player.inputSeq=msg.seq;player.inputPosition=Math.max(0,Math.min(1,msg.position));player.lastSeenAt=new Date();this.pendingInputs.set(player.id,cloneInput(player));this.markDirty();}
 async admin(ws){const client=this.clients.get(ws);if(!client||client.playerId!==this.state.adminPlayerId)return;if(!this.rate(client,'adminCount',this.options.adminRate)){ws.close(4429,'admin rate limit');return;}await this.syncExternal(true);}
 markDirty(){this.dirty=true;this.mutation++;}
 onTick(){if(this.stopped||this.syncing)return;const at=now(),room=this.publicRoom();advance(room,Math.min(50,at-this.lastTick));this.lastTick=at;this.state.scoreLeft=room.scores.left;this.state.scoreRight=room.scores.right;Object.assign(this.state,{ballX:room.ball.x,ballY:room.ball.y,ballVx:room.ball.vx,ballVy:room.ball.vy});if(this.state.status==='playing')this.markDirty();}
 async onBroadcast(){if(this.stopped||!this.clients.size)return;if(now()-this.lastRefresh>=this.options.refreshMs)await this.syncExternal(false);this.broadcastNow();}
 broadcastNow(){if(!this.clients.size)return;const payload=JSON.stringify({type:'snapshot',seq:++this.seq,serverTime:now(),room:this.publicRoom()});for(const[ws,client]of this.clients){if(ws.readyState!==1)continue;if((ws.bufferedAmount??0)>this.options.maxBufferedAmount){client.backpressureStrikes++;if(client.backpressureStrikes>=this.options.maxBackpressureStrikes){this.remove(ws);ws.close(4410,'client too slow');}continue;}client.backpressureStrikes=0;ws.send(payload);}}
 async checkpoint(){if(!this.dirty)return;if(this.checkpointPromise)return this.checkpointPromise;this.checkpointPromise=this.doCheckpoint().finally(()=>{this.checkpointPromise=null;});return this.checkpointPromise;}
 async checkpointUntilClean(maxAttempts=this.options.finalCheckpointAttempts,shouldContinue=()=>true){let lastError;for(let attempt=0;this.dirty&&attempt<maxAttempts;attempt++){if(!shouldContinue())return false;try{await this.checkpoint();lastError=undefined;}catch(error){lastError=error;if(attempt+1<maxAttempts&&shouldContinue())await new Promise(resolve=>setTimeout(resolve,this.options.finalCheckpointBackoffMs));}}if(!shouldContinue())return false;if(this.dirty){if(lastError)throw lastError;const error=new Error('checkpoint remained dirty');error.code='DNP_CHECKPOINT_INCOMPLETE';throw error;}return true;}
 async doCheckpoint(){const expected=this.state.version,generation=this.mutation,players=this.state.players.filter(p=>!p.leftAt).map(cloneInput);try{const result=await this.adapter.checkpoint(this.state,expected,players);this.state.version=result?.version??expected+1;for(const p of players){const pending=this.pendingInputs.get(p.id);if(pending&&pending.inputSeq<=p.inputSeq)this.pendingInputs.delete(p.id);}if(this.mutation===generation)this.dirty=false;}catch(error){if(error?.code!=='DNP_CONFLICT'){this.dirty=true;throw error;}await this.resync();}}
 async resync(){const fresh=await this.adapter.refresh(this.code);if(!fresh)throw new Error('room unavailable during resync');this.applyFresh(fresh,true);this.dirty=this.pendingInputs.size>0||this.state.status==='playing';}
 applyFresh(fresh,preservePending){const pending=preservePending?new Map(this.pendingInputs):new Map();this.state=fresh;for(const [id,input]of pending){const player=this.state.players.find(p=>p.id===id&&!p.leftAt);if(player&&input.inputSeq>player.inputSeq){player.inputSeq=input.inputSeq;player.inputPosition=input.inputPosition;}else this.pendingInputs.delete(id);}this.revokeInactive();}
 revokeInactive(){for(const[ws,client]of this.clients){const active=this.state.players.some(p=>p.id===client.playerId&&!p.leftAt);if(!active){this.remove(ws);ws.close(4403,'player no longer active');}}}
 async syncExternal(force=false){if(this.syncPromise)return this.syncPromise;if(!force&&now()-this.lastRefresh<this.options.refreshMs)return;this.lastRefresh=now();this.syncing=true;this.syncPromise=(async()=>{if(this.dirty)await this.checkpoint();const fresh=await this.adapter.refresh(this.code);if(fresh&&fresh.version>=this.state.version)this.applyFresh(fresh,true);this.revokeInactive();if(force)this.broadcastNow();})().finally(()=>{this.syncing=false;this.lastTick=now();this.syncPromise=null;});return this.syncPromise;}
 async touchPresence(at=now()){if(at-this.lastPresence<this.options.presenceMs)return;this.lastPresence=at;const ids=[...new Set([...this.clients.values()].map(c=>c.playerId))];if(!ids.length)return;await this.adapter.touchPresence?.(ids);const date=new Date(at);for(const p of this.state.players)if(ids.includes(p.id))p.lastSeenAt=date;}
 async shutdown(){if(this.stopped)return;this.quiesce();await this.checkpointUntilClean();this.stop();}
 stop(){if(this.stopped)return;this.stopped=true;this.pauseTimers();clearTimeout(this.idleTimer);}
}
