import type { DnpPublicRoom } from '@/lib/dnp/domain';
import { DNP_INPUT_EPSILON } from './multiplayer-client';
export type DnpSocketConnectionState='connecting'|'realtime'|'reconnecting'|'fallback';
export type DnpSocketTicketResponse={url:string;ticket:string};
export function shouldSendSocketInput(previous:number|null,next:number){return previous===null||Math.abs(previous-next)>=DNP_INPUT_EPSILON;}
type SocketLike=Pick<WebSocket,'readyState'|'send'|'close'|'addEventListener'>;
type Options={code:string;token:string;playerId?:string;fetchTicket?:()=>Promise<DnpSocketTicketResponse>;createSocket?:(url:string)=>SocketLike;onSnapshot:(room:DnpPublicRoom,seq:number)=>void;onState?:(state:DnpSocketConnectionState)=>void;maxFailures?:number;watchdogMs?:number;reconnectDelaysMs?:number[]};
export class DnpSocketTransport{
 private socket:SocketLike|null=null;private stopped=false;private failures=0;private snapshotSeq=-1;private inputSeq=0;private lastInput:number|null=null;private lastInputAt=0;private reconnectTimer:ReturnType<typeof setTimeout>|null=null;private watchdog:ReturnType<typeof setTimeout>|null=null;private attempt=0;private reconnectScheduled=false;private gotSnapshot=false;
 constructor(private options:Options){}
 async start(){this.stopped=false;await this.connect(false);}
 private async connect(reconnecting:boolean){if(this.stopped)return;this.clearAttempt();this.reconnectScheduled=false;this.attempt++;const attempt=this.attempt;this.snapshotSeq=-1;this.gotSnapshot=false;this.lastInput=null;this.options.onState?.(reconnecting?'reconnecting':'connecting');this.armWatchdog(attempt);try{const credentials=await(this.options.fetchTicket??(()=>this.fetchTicket()))();if(this.stopped||attempt!==this.attempt||this.reconnectScheduled)return;const socket=(this.options.createSocket??(url=>new WebSocket(url)))(credentials.url);this.socket=socket;await new Promise<void>((resolve,reject)=>{let settled=false;const settle=(error?:Error)=>{if(settled)return;settled=true;error?reject(error):resolve();};socket.addEventListener('open',()=>{if(attempt!==this.attempt)return;socket.send(JSON.stringify({type:'auth',ticket:credentials.ticket}));settle();});socket.addEventListener('message',(event:MessageEvent)=>this.onMessage(event.data,attempt));socket.addEventListener('error',()=>{settle(new Error('WebSocket failed.'));this.failAttempt(attempt);});socket.addEventListener('close',()=>{settle();this.failAttempt(attempt);});});}catch{this.failAttempt(attempt);}}
 private armWatchdog(attempt:number){if(this.watchdog)clearTimeout(this.watchdog);this.watchdog=setTimeout(()=>{if(attempt!==this.attempt)return;this.socket?.close();this.failAttempt(attempt);},this.options.watchdogMs??8000);}
 private clearAttempt(){if(this.watchdog)clearTimeout(this.watchdog);this.watchdog=null;}
 private async fetchTicket(){const response=await fetch(`/api/dnp/rooms/${this.options.code}/socket-ticket`,{method:'POST',headers:{Authorization:`Bearer ${this.options.token}`}});const payload=await response.json() as Partial<DnpSocketTicketResponse>&{error?:string};if(!response.ok||!payload.url||!payload.ticket)throw new Error(payload.error??'Realtime unavailable.');return payload as DnpSocketTicketResponse;}
 private onMessage(data:unknown,attempt:number){if(attempt!==this.attempt)return;try{const message=JSON.parse(String(data)) as{type?:string;seq?:number;room?:DnpPublicRoom};if(message.type==='snapshot'&&Number.isInteger(message.seq)&&message.room&&(message.seq as number)>this.snapshotSeq){this.gotSnapshot=true;this.armWatchdog(attempt);this.failures=0;this.options.onState?.('realtime');this.snapshotSeq=message.seq as number;const own=message.room.players.find(player=>player.id===this.options.playerId);if(own)this.inputSeq=Math.max(this.inputSeq,own.inputSeq);this.options.onSnapshot(message.room,message.seq as number);}}catch{}}
 private failAttempt(attempt:number){if(this.stopped||attempt!==this.attempt||this.reconnectScheduled)return;this.clearAttempt();this.reconnectScheduled=true;this.failures++;if(this.failures>=(this.options.maxFailures??5)){this.options.onState?.('fallback');return;}this.options.onState?.('reconnecting');const configured=this.options.reconnectDelaysMs,delay=configured?.[Math.min(this.failures-1,configured.length-1)]??Math.min(4000,250*2**(this.failures-1));this.reconnectTimer=setTimeout(()=>void this.connect(true),delay);}
 sendInput(position:number,at=Date.now()){if(!this.socket||this.socket.readyState!==1||at-this.lastInputAt<1000/30||!shouldSendSocketInput(this.lastInput,position))return false;if(this.inputSeq>=2147483647)return false;this.inputSeq++;this.lastInput=position;this.lastInputAt=at;this.socket.send(JSON.stringify({type:'input',seq:this.inputSeq,position}));return true;}
 sendAdmin(action:string,payload:Record<string,unknown>={}){if(!this.socket||this.socket.readyState!==1)return false;this.socket.send(JSON.stringify({type:'admin',action,...payload}));return true;}
 requestSync(){if(!this.socket||this.socket.readyState!==1)return false;this.socket.send(JSON.stringify({type:'sync'}));return true;}
 stop(){this.stopped=true;this.attempt++;this.clearAttempt();if(this.reconnectTimer)clearTimeout(this.reconnectTimer);this.reconnectTimer=null;const socket=this.socket;this.socket=null;socket?.close();}
}
